use_frameworks!

platform :ios, '9.0'

target 'TWInputCell_Example' do
  pod 'TWInputCell', :path => '../'

  target 'TWInputCell_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
